[experiment]
    exp_name = "science_ie_tagger"
    exp_dir = "science_ie_tagger_toml"

[dataset]
	class = "CoNLLDatasetManager"
	train_filename="train_science_ie_conll.txt"
	dev_filename="dev_science_ie_conll.txt"
	test_filename="dev_science_ie_conll.txt"
	column_names=["TASK", "PROCESS", "MATERIAL"]



[model]
    class="RnnSeqCrfTagger"
    encoding_dim=20
    tagging_type="BIOUL"
    [model.rnn2seqencoder]
        class="Lstm2SeqEncoder"
        dropout_value = 0.5
        hidden_dim=20
        bidirectional=false
        num_layers=1
        combine_strategy="concat"
        rnn_bias=true
        [[model.rnn2seqencoder.embedder]]
        class="WordEmbedder"
        embedding_type="glove_6B_50"
        [[model.rnn2seqencoder.embedder]]
        class="CharEmbedder"
        char_embedding_dimension=5
        hidden_dimension=10



[engine]
    batch_size=32
    save_dir="science_ie_tagger_toml/checkpoints"
    num_epochs=1
    save_every=10
    log_train_metrics_every=10
    device="cpu"
    gradient_norm_clip_value=5.0
    [engine.metric]
        class="TokenClassificationAccuracy"
    [engine.optimizer]
        class="Adam"
        lr=1e-3