[experiment]
    exp_name = "sectlabel-bow-bert"
    exp_dir = "sectlabel_bow_bert_toml"

[dataset]
	class = "TextClassificationDatasetManager"
	train_filename="sectLabel.train"
	dev_filename="sectLabel.dev"
	test_filename="sectLabel.test"

[model]
    class="SimpleClassifier"
    encoding_dim=768
    num_classes=23
    classification_layer_bias=true
    [model.encoder]
        class="BOW_Encoder"
        dropout_value = 0.5
        aggregation_type="sum"
        [[model.encoder.embedder]]
        class="BertEmbedder"
        bert_type="bert-base-cased"
        aggregation_type="average"

[engine]
    batch_size=32
    save_dir="sectlabel_bow_bert_toml/checkpoints"
    num_epochs=1
    save_every=10
    log_train_metrics_every=10
    device="cpu"
    gradient_norm_clip_value=5.0
    sample_proportion=0.01
    [engine.metric]
        class="PrecisionRecallFMeasure"
    [engine.optimizer]
        class="Adam"
        lr=1e-3